// Code generated by MockGen. DO NOT EDIT.
// Source: workoutpal/src/internal/domain/service (interfaces: ExerciseSettingService)

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"
	model "workoutpal/src/internal/model"

	gomock "github.com/golang/mock/gomock"
)

// MockExerciseSettingService is a mock of ExerciseSettingService interface.
type MockExerciseSettingService struct {
	ctrl     *gomock.Controller
	recorder *MockExerciseSettingServiceMockRecorder
}

// MockExerciseSettingServiceMockRecorder is the mock recorder for MockExerciseSettingService.
type MockExerciseSettingServiceMockRecorder struct {
	mock *MockExerciseSettingService
}

// NewMockExerciseSettingService creates a new mock instance.
func NewMockExerciseSettingService(ctrl *gomock.Controller) *MockExerciseSettingService {
	mock := &MockExerciseSettingService{ctrl: ctrl}
	mock.recorder = &MockExerciseSettingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExerciseSettingService) EXPECT() *MockExerciseSettingServiceMockRecorder {
	return m.recorder
}

// CreateExerciseSetting mocks base method.
func (m *MockExerciseSettingService) CreateExerciseSetting(arg0 model.CreateExerciseSettingRequest) (*model.ExerciseSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExerciseSetting", arg0)
	ret0, _ := ret[0].(*model.ExerciseSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExerciseSetting indicates an expected call of CreateExerciseSetting.
func (mr *MockExerciseSettingServiceMockRecorder) CreateExerciseSetting(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExerciseSetting", reflect.TypeOf((*MockExerciseSettingService)(nil).CreateExerciseSetting), arg0)
}

// ReadExerciseSetting mocks base method.
func (m *MockExerciseSettingService) ReadExerciseSetting(arg0 model.ReadExerciseSettingRequest) (*model.ExerciseSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadExerciseSetting", arg0)
	ret0, _ := ret[0].(*model.ExerciseSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadExerciseSetting indicates an expected call of ReadExerciseSetting.
func (mr *MockExerciseSettingServiceMockRecorder) ReadExerciseSetting(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadExerciseSetting", reflect.TypeOf((*MockExerciseSettingService)(nil).ReadExerciseSetting), arg0)
}

// UpdateExerciseSetting mocks base method.
func (m *MockExerciseSettingService) UpdateExerciseSetting(arg0 model.UpdateExerciseSettingRequest) (*model.ExerciseSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExerciseSetting", arg0)
	ret0, _ := ret[0].(*model.ExerciseSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateExerciseSetting indicates an expected call of UpdateExerciseSetting.
func (mr *MockExerciseSettingServiceMockRecorder) UpdateExerciseSetting(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExerciseSetting", reflect.TypeOf((*MockExerciseSettingService)(nil).UpdateExerciseSetting), arg0)
}
