// Code generated by MockGen. DO NOT EDIT.
// Source: workoutpal/src/internal/domain/service (interfaces: PostService)

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"
	model "workoutpal/src/internal/model"

	gomock "github.com/golang/mock/gomock"
)

// MockPostService is a mock of PostService interface.
type MockPostService struct {
	ctrl     *gomock.Controller
	recorder *MockPostServiceMockRecorder
}

// MockPostServiceMockRecorder is the mock recorder for MockPostService.
type MockPostServiceMockRecorder struct {
	mock *MockPostService
}

// NewMockPostService creates a new mock instance.
func NewMockPostService(ctrl *gomock.Controller) *MockPostService {
	mock := &MockPostService{ctrl: ctrl}
	mock.recorder = &MockPostServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostService) EXPECT() *MockPostServiceMockRecorder {
	return m.recorder
}

// CommentOnComment mocks base method.
func (m *MockPostService) CommentOnComment(arg0 model.CommentOnCommentRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommentOnComment", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommentOnComment indicates an expected call of CommentOnComment.
func (mr *MockPostServiceMockRecorder) CommentOnComment(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommentOnComment", reflect.TypeOf((*MockPostService)(nil).CommentOnComment), arg0)
}

// CommentOnPost mocks base method.
func (m *MockPostService) CommentOnPost(arg0 model.CommentOnPostRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommentOnPost", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommentOnPost indicates an expected call of CommentOnPost.
func (mr *MockPostServiceMockRecorder) CommentOnPost(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommentOnPost", reflect.TypeOf((*MockPostService)(nil).CommentOnPost), arg0)
}

// CreatePost mocks base method.
func (m *MockPostService) CreatePost(arg0 model.CreatePostRequest) (*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", arg0)
	ret0, _ := ret[0].(*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockPostServiceMockRecorder) CreatePost(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockPostService)(nil).CreatePost), arg0)
}

// DeletePost mocks base method.
func (m *MockPostService) DeletePost(arg0 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePost", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePost indicates an expected call of DeletePost.
func (mr *MockPostServiceMockRecorder) DeletePost(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePost", reflect.TypeOf((*MockPostService)(nil).DeletePost), arg0)
}

// LikePost mocks base method.
func (m *MockPostService) LikePost(arg0 model.LikePostRequest) (*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LikePost", arg0)
	ret0, _ := ret[0].(*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LikePost indicates an expected call of LikePost.
func (mr *MockPostServiceMockRecorder) LikePost(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LikePost", reflect.TypeOf((*MockPostService)(nil).LikePost), arg0)
}

// ReadPosts mocks base method.
func (m *MockPostService) ReadPosts(arg0 int64) ([]*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPosts", arg0)
	ret0, _ := ret[0].([]*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadPosts indicates an expected call of ReadPosts.
func (mr *MockPostServiceMockRecorder) ReadPosts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPosts", reflect.TypeOf((*MockPostService)(nil).ReadPosts), arg0)
}

// ReadPostsByUserID mocks base method.
func (m *MockPostService) ReadPostsByUserID(arg0, arg1 int64) ([]*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPostsByUserID", arg0, arg1)
	ret0, _ := ret[0].([]*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadPostsByUserID indicates an expected call of ReadPostsByUserID.
func (mr *MockPostServiceMockRecorder) ReadPostsByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPostsByUserID", reflect.TypeOf((*MockPostService)(nil).ReadPostsByUserID), arg0, arg1)
}

// UnlikePost mocks base method.
func (m *MockPostService) UnlikePost(arg0 model.UnikePostRequest) (*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlikePost", arg0)
	ret0, _ := ret[0].(*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnlikePost indicates an expected call of UnlikePost.
func (mr *MockPostServiceMockRecorder) UnlikePost(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlikePost", reflect.TypeOf((*MockPostService)(nil).UnlikePost), arg0)
}

// UpdatePost mocks base method.
func (m *MockPostService) UpdatePost(arg0 model.UpdatePostRequest) (*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePost", arg0)
	ret0, _ := ret[0].(*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePost indicates an expected call of UpdatePost.
func (mr *MockPostServiceMockRecorder) UpdatePost(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePost", reflect.TypeOf((*MockPostService)(nil).UpdatePost), arg0)
}
