// Code generated by MockGen. DO NOT EDIT.
// Source: workoutpal/src/internal/domain/service (interfaces: RelationshipService)

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"
	model "workoutpal/src/internal/model"

	gomock "github.com/golang/mock/gomock"
)

// MockRelationshipService is a mock of RelationshipService interface.
type MockRelationshipService struct {
	ctrl     *gomock.Controller
	recorder *MockRelationshipServiceMockRecorder
}

// MockRelationshipServiceMockRecorder is the mock recorder for MockRelationshipService.
type MockRelationshipServiceMockRecorder struct {
	mock *MockRelationshipService
}

// NewMockRelationshipService creates a new mock instance.
func NewMockRelationshipService(ctrl *gomock.Controller) *MockRelationshipService {
	mock := &MockRelationshipService{ctrl: ctrl}
	mock.recorder = &MockRelationshipServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRelationshipService) EXPECT() *MockRelationshipServiceMockRecorder {
	return m.recorder
}

// FollowUser mocks base method.
func (m *MockRelationshipService) FollowUser(arg0, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FollowUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// FollowUser indicates an expected call of FollowUser.
func (mr *MockRelationshipServiceMockRecorder) FollowUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FollowUser", reflect.TypeOf((*MockRelationshipService)(nil).FollowUser), arg0, arg1)
}

// ReadUserFollowers mocks base method.
func (m *MockRelationshipService) ReadUserFollowers(arg0 int64) ([]model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadUserFollowers", arg0)
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadUserFollowers indicates an expected call of ReadUserFollowers.
func (mr *MockRelationshipServiceMockRecorder) ReadUserFollowers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadUserFollowers", reflect.TypeOf((*MockRelationshipService)(nil).ReadUserFollowers), arg0)
}

// ReadUserFollowing mocks base method.
func (m *MockRelationshipService) ReadUserFollowing(arg0 int64) ([]model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadUserFollowing", arg0)
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadUserFollowing indicates an expected call of ReadUserFollowing.
func (mr *MockRelationshipServiceMockRecorder) ReadUserFollowing(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadUserFollowing", reflect.TypeOf((*MockRelationshipService)(nil).ReadUserFollowing), arg0)
}

// UnfollowUser mocks base method.
func (m *MockRelationshipService) UnfollowUser(arg0, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnfollowUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnfollowUser indicates an expected call of UnfollowUser.
func (mr *MockRelationshipServiceMockRecorder) UnfollowUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnfollowUser", reflect.TypeOf((*MockRelationshipService)(nil).UnfollowUser), arg0, arg1)
}

// SendFollowRequest mocks base method.
func (m *MockRelationshipService) SendFollowRequest(arg0, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendFollowRequest", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendFollowRequest indicates an expected call of SendFollowRequest.
func (mr *MockRelationshipServiceMockRecorder) SendFollowRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFollowRequest", reflect.TypeOf((*MockRelationshipService)(nil).SendFollowRequest), arg0, arg1)
}

// GetFollowRequest mocks base method.
func (m *MockRelationshipService) GetFollowRequest(arg0, arg1 int64) (*model.FollowRequestModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowRequest", arg0, arg1)
	ret0, _ := ret[0].(*model.FollowRequestModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowRequest indicates an expected call of GetFollowRequest.
func (mr *MockRelationshipServiceMockRecorder) GetFollowRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowRequest", reflect.TypeOf((*MockRelationshipService)(nil).GetFollowRequest), arg0, arg1)
}

// GetPendingFollowRequests mocks base method.
func (m *MockRelationshipService) GetPendingFollowRequests(arg0 int64) ([]*model.FollowRequestWithUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingFollowRequests", arg0)
	ret0, _ := ret[0].([]*model.FollowRequestWithUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingFollowRequests indicates an expected call of GetPendingFollowRequests.
func (mr *MockRelationshipServiceMockRecorder) GetPendingFollowRequests(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingFollowRequests", reflect.TypeOf((*MockRelationshipService)(nil).GetPendingFollowRequests), arg0)
}

// AcceptFollowRequest mocks base method.
func (m *MockRelationshipService) AcceptFollowRequest(arg0 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptFollowRequest", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptFollowRequest indicates an expected call of AcceptFollowRequest.
func (mr *MockRelationshipServiceMockRecorder) AcceptFollowRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptFollowRequest", reflect.TypeOf((*MockRelationshipService)(nil).AcceptFollowRequest), arg0)
}

// RejectFollowRequest mocks base method.
func (m *MockRelationshipService) RejectFollowRequest(arg0 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectFollowRequest", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectFollowRequest indicates an expected call of RejectFollowRequest.
func (mr *MockRelationshipServiceMockRecorder) RejectFollowRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectFollowRequest", reflect.TypeOf((*MockRelationshipService)(nil).RejectFollowRequest), arg0)
}

// CancelFollowRequest mocks base method.
func (m *MockRelationshipService) CancelFollowRequest(arg0, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelFollowRequest", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelFollowRequest indicates an expected call of CancelFollowRequest.
func (mr *MockRelationshipServiceMockRecorder) CancelFollowRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelFollowRequest", reflect.TypeOf((*MockRelationshipService)(nil).CancelFollowRequest), arg0, arg1)
}
