// Code generated by MockGen. DO NOT EDIT.
// Source: workoutpal/src/internal/domain/service (interfaces: AchievementService)

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"
	model "workoutpal/src/internal/model"

	gomock "github.com/golang/mock/gomock"
)

// MockAchievementService is a mock of AchievementService interface.
type MockAchievementService struct {
	ctrl     *gomock.Controller
	recorder *MockAchievementServiceMockRecorder
}

// MockAchievementServiceMockRecorder is the mock recorder for MockAchievementService.
type MockAchievementServiceMockRecorder struct {
	mock *MockAchievementService
}

// NewMockAchievementService creates a new mock instance.
func NewMockAchievementService(ctrl *gomock.Controller) *MockAchievementService {
	mock := &MockAchievementService{ctrl: ctrl}
	mock.recorder = &MockAchievementServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAchievementService) EXPECT() *MockAchievementServiceMockRecorder {
	return m.recorder
}

// CreateAchievement mocks base method.
func (m *MockAchievementService) CreateAchievement(arg0 model.CreateAchievementRequest) (*model.Achievement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAchievement", arg0)
	ret0, _ := ret[0].(*model.Achievement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAchievement indicates an expected call of CreateAchievement.
func (mr *MockAchievementServiceMockRecorder) CreateAchievement(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAchievement", reflect.TypeOf((*MockAchievementService)(nil).CreateAchievement), arg0)
}

// DeleteAchievement mocks base method.
func (m *MockAchievementService) DeleteAchievement(arg0 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAchievement", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAchievement indicates an expected call of DeleteAchievement.
func (mr *MockAchievementServiceMockRecorder) DeleteAchievement(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAchievement", reflect.TypeOf((*MockAchievementService)(nil).DeleteAchievement), arg0)
}

// ReadAchievements mocks base method.
func (m *MockAchievementService) ReadAchievements(arg0 int64) ([]*model.Achievement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAchievements", arg0)
	ret0, _ := ret[0].([]*model.Achievement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAchievements indicates an expected call of ReadAchievements.
func (mr *MockAchievementServiceMockRecorder) ReadAchievements(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAchievements", reflect.TypeOf((*MockAchievementService)(nil).ReadAchievements), arg0)
}
