// Code generated by MockGen. DO NOT EDIT.
// Source: workoutpal/src/internal/domain/service (interfaces: AchievementService)

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"
	model "workoutpal/src/internal/model"

	gomock "github.com/golang/mock/gomock"
)

// MockAchievementService is a mock of AchievementService interface.
type MockAchievementService struct {
	ctrl     *gomock.Controller
	recorder *MockAchievementServiceMockRecorder
}

// MockAchievementServiceMockRecorder is the mock recorder for MockAchievementService.
type MockAchievementServiceMockRecorder struct {
	mock *MockAchievementService
}

// NewMockAchievementService creates a new mock instance.
func NewMockAchievementService(ctrl *gomock.Controller) *MockAchievementService {
	mock := &MockAchievementService{ctrl: ctrl}
	mock.recorder = &MockAchievementServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAchievementService) EXPECT() *MockAchievementServiceMockRecorder {
	return m.recorder
}

// CreateAchievement mocks base method.
func (m *MockAchievementService) CreateAchievement(arg0 model.CreateAchievementRequest) (*model.UserAchievement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAchievement", arg0)
	ret0, _ := ret[0].(*model.UserAchievement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAchievement indicates an expected call of CreateAchievement.
func (mr *MockAchievementServiceMockRecorder) CreateAchievement(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAchievement", reflect.TypeOf((*MockAchievementService)(nil).CreateAchievement), arg0)
}

// ReadAchievementsFeed mocks base method.
func (m *MockAchievementService) ReadAchievementsFeed() ([]*model.UserAchievement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAchievementsFeed")
	ret0, _ := ret[0].([]*model.UserAchievement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAchievementsFeed indicates an expected call of ReadAchievementsFeed.
func (mr *MockAchievementServiceMockRecorder) ReadAchievementsFeed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAchievementsFeed", reflect.TypeOf((*MockAchievementService)(nil).ReadAchievementsFeed))
}

// ReadAllAchievements mocks base method.
func (m *MockAchievementService) ReadAllAchievements() ([]*model.Achievement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAllAchievements")
	ret0, _ := ret[0].([]*model.Achievement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAllAchievements indicates an expected call of ReadAllAchievements.
func (mr *MockAchievementServiceMockRecorder) ReadAllAchievements() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAllAchievements", reflect.TypeOf((*MockAchievementService)(nil).ReadAllAchievements))
}

// ReadUnlockedAchievements mocks base method.
func (m *MockAchievementService) ReadUnlockedAchievements(arg0 int64) ([]*model.UserAchievement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadUnlockedAchievements", arg0)
	ret0, _ := ret[0].([]*model.UserAchievement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadUnlockedAchievements indicates an expected call of ReadUnlockedAchievements.
func (mr *MockAchievementServiceMockRecorder) ReadUnlockedAchievements(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadUnlockedAchievements", reflect.TypeOf((*MockAchievementService)(nil).ReadUnlockedAchievements), arg0)
}
