// Code generated by MockGen. DO NOT EDIT.
// Source: workoutpal/src/internal/domain/repository (interfaces: ExerciseSettingRepository)

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"
	model "workoutpal/src/internal/model"

	gomock "github.com/golang/mock/gomock"
)

// MockExerciseSettingRepository is a mock of ExerciseSettingRepository interface.
type MockExerciseSettingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExerciseSettingRepositoryMockRecorder
}

// MockExerciseSettingRepositoryMockRecorder is the mock recorder for MockExerciseSettingRepository.
type MockExerciseSettingRepositoryMockRecorder struct {
	mock *MockExerciseSettingRepository
}

// NewMockExerciseSettingRepository creates a new mock instance.
func NewMockExerciseSettingRepository(ctrl *gomock.Controller) *MockExerciseSettingRepository {
	mock := &MockExerciseSettingRepository{ctrl: ctrl}
	mock.recorder = &MockExerciseSettingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExerciseSettingRepository) EXPECT() *MockExerciseSettingRepositoryMockRecorder {
	return m.recorder
}

// CreateExerciseSetting mocks base method.
func (m *MockExerciseSettingRepository) CreateExerciseSetting(arg0 model.CreateExerciseSettingRequest) (*model.ExerciseSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExerciseSetting", arg0)
	ret0, _ := ret[0].(*model.ExerciseSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExerciseSetting indicates an expected call of CreateExerciseSetting.
func (mr *MockExerciseSettingRepositoryMockRecorder) CreateExerciseSetting(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExerciseSetting", reflect.TypeOf((*MockExerciseSettingRepository)(nil).CreateExerciseSetting), arg0)
}

// ReadExerciseSetting mocks base method.
func (m *MockExerciseSettingRepository) ReadExerciseSetting(arg0 model.ReadExerciseSettingRequest) (*model.ExerciseSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadExerciseSetting", arg0)
	ret0, _ := ret[0].(*model.ExerciseSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadExerciseSetting indicates an expected call of ReadExerciseSetting.
func (mr *MockExerciseSettingRepositoryMockRecorder) ReadExerciseSetting(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadExerciseSetting", reflect.TypeOf((*MockExerciseSettingRepository)(nil).ReadExerciseSetting), arg0)
}

// UpdateExerciseSetting mocks base method.
func (m *MockExerciseSettingRepository) UpdateExerciseSetting(arg0 model.UpdateExerciseSettingRequest) (*model.ExerciseSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExerciseSetting", arg0)
	ret0, _ := ret[0].(*model.ExerciseSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateExerciseSetting indicates an expected call of UpdateExerciseSetting.
func (mr *MockExerciseSettingRepositoryMockRecorder) UpdateExerciseSetting(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExerciseSetting", reflect.TypeOf((*MockExerciseSettingRepository)(nil).UpdateExerciseSetting), arg0)
}
