// Code generated by MockGen. DO NOT EDIT.
// Source: workoutpal/src/internal/domain/repository (interfaces: PostRepository)

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"
	model "workoutpal/src/internal/model"

	gomock "github.com/golang/mock/gomock"
)

// MockPostRepository is a mock of PostRepository interface.
type MockPostRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPostRepositoryMockRecorder
}

// MockPostRepositoryMockRecorder is the mock recorder for MockPostRepository.
type MockPostRepositoryMockRecorder struct {
	mock *MockPostRepository
}

// NewMockPostRepository creates a new mock instance.
func NewMockPostRepository(ctrl *gomock.Controller) *MockPostRepository {
	mock := &MockPostRepository{ctrl: ctrl}
	mock.recorder = &MockPostRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostRepository) EXPECT() *MockPostRepositoryMockRecorder {
	return m.recorder
}

// CommentOnComment mocks base method.
func (m *MockPostRepository) CommentOnComment(arg0 model.CommentOnCommentRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommentOnComment", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommentOnComment indicates an expected call of CommentOnComment.
func (mr *MockPostRepositoryMockRecorder) CommentOnComment(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommentOnComment", reflect.TypeOf((*MockPostRepository)(nil).CommentOnComment), arg0)
}

// CommentOnPost mocks base method.
func (m *MockPostRepository) CommentOnPost(arg0 model.CommentOnPostRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommentOnPost", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommentOnPost indicates an expected call of CommentOnPost.
func (mr *MockPostRepositoryMockRecorder) CommentOnPost(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommentOnPost", reflect.TypeOf((*MockPostRepository)(nil).CommentOnPost), arg0)
}

// CreatePost mocks base method.
func (m *MockPostRepository) CreatePost(arg0 model.CreatePostRequest) (*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", arg0)
	ret0, _ := ret[0].(*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockPostRepositoryMockRecorder) CreatePost(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockPostRepository)(nil).CreatePost), arg0)
}

// DeletePost mocks base method.
func (m *MockPostRepository) DeletePost(arg0 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePost", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePost indicates an expected call of DeletePost.
func (mr *MockPostRepositoryMockRecorder) DeletePost(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePost", reflect.TypeOf((*MockPostRepository)(nil).DeletePost), arg0)
}

// ReadCommentsByComment mocks base method.
func (m *MockPostRepository) ReadCommentsByComment(arg0 int64) ([]*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadCommentsByComment", arg0)
	ret0, _ := ret[0].([]*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadCommentsByComment indicates an expected call of ReadCommentsByComment.
func (mr *MockPostRepositoryMockRecorder) ReadCommentsByComment(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadCommentsByComment", reflect.TypeOf((*MockPostRepository)(nil).ReadCommentsByComment), arg0)
}

// ReadCommentsByPost mocks base method.
func (m *MockPostRepository) ReadCommentsByPost(arg0 int64) ([]*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadCommentsByPost", arg0)
	ret0, _ := ret[0].([]*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadCommentsByPost indicates an expected call of ReadCommentsByPost.
func (mr *MockPostRepositoryMockRecorder) ReadCommentsByPost(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadCommentsByPost", reflect.TypeOf((*MockPostRepository)(nil).ReadCommentsByPost), arg0)
}

// ReadPost mocks base method.
func (m *MockPostRepository) ReadPost(arg0 int64) (*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPost", arg0)
	ret0, _ := ret[0].(*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadPost indicates an expected call of ReadPost.
func (mr *MockPostRepositoryMockRecorder) ReadPost(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPost", reflect.TypeOf((*MockPostRepository)(nil).ReadPost), arg0)
}

// ReadPosts mocks base method.
func (m *MockPostRepository) ReadPosts() ([]*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPosts")
	ret0, _ := ret[0].([]*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadPosts indicates an expected call of ReadPosts.
func (mr *MockPostRepositoryMockRecorder) ReadPosts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPosts", reflect.TypeOf((*MockPostRepository)(nil).ReadPosts))
}

// ReadPostsByUserId mocks base method.
func (m *MockPostRepository) ReadPostsByUserId(arg0 int64) ([]*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPostsByUserId", arg0)
	ret0, _ := ret[0].([]*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadPostsByUserId indicates an expected call of ReadPostsByUserId.
func (mr *MockPostRepositoryMockRecorder) ReadPostsByUserId(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPostsByUserId", reflect.TypeOf((*MockPostRepository)(nil).ReadPostsByUserId), arg0)
}

// UpdatePost mocks base method.
func (m *MockPostRepository) UpdatePost(arg0 model.UpdatePostRequest) (*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePost", arg0)
	ret0, _ := ret[0].(*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePost indicates an expected call of UpdatePost.
func (mr *MockPostRepositoryMockRecorder) UpdatePost(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePost", reflect.TypeOf((*MockPostRepository)(nil).UpdatePost), arg0)
}
