// Code generated by MockGen. DO NOT EDIT.
// Source: workoutpal/src/internal/domain/repository (interfaces: AchievementRepository)

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"
	model "workoutpal/src/internal/model"

	gomock "github.com/golang/mock/gomock"
)

// MockAchievementRepository is a mock of AchievementRepository interface.
type MockAchievementRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAchievementRepositoryMockRecorder
}

// MockAchievementRepositoryMockRecorder is the mock recorder for MockAchievementRepository.
type MockAchievementRepositoryMockRecorder struct {
	mock *MockAchievementRepository
}

// NewMockAchievementRepository creates a new mock instance.
func NewMockAchievementRepository(ctrl *gomock.Controller) *MockAchievementRepository {
	mock := &MockAchievementRepository{ctrl: ctrl}
	mock.recorder = &MockAchievementRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAchievementRepository) EXPECT() *MockAchievementRepositoryMockRecorder {
	return m.recorder
}

// CreateAchievement mocks base method.
func (m *MockAchievementRepository) CreateAchievement(arg0 model.CreateAchievementRequest) (*model.UserAchievement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAchievement", arg0)
	ret0, _ := ret[0].(*model.UserAchievement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAchievement indicates an expected call of CreateAchievement.
func (mr *MockAchievementRepositoryMockRecorder) CreateAchievement(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAchievement", reflect.TypeOf((*MockAchievementRepository)(nil).CreateAchievement), arg0)
}

// ReadAchievementsFeed mocks base method.
func (m *MockAchievementRepository) ReadAchievementsFeed() ([]*model.UserAchievement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAchievementsFeed")
	ret0, _ := ret[0].([]*model.UserAchievement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAchievementsFeed indicates an expected call of ReadAchievementsFeed.
func (mr *MockAchievementRepositoryMockRecorder) ReadAchievementsFeed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAchievementsFeed", reflect.TypeOf((*MockAchievementRepository)(nil).ReadAchievementsFeed))
}

// ReadAllAchievements mocks base method.
func (m *MockAchievementRepository) ReadAllAchievements() ([]*model.Achievement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAllAchievements")
	ret0, _ := ret[0].([]*model.Achievement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAllAchievements indicates an expected call of ReadAllAchievements.
func (mr *MockAchievementRepositoryMockRecorder) ReadAllAchievements() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAllAchievements", reflect.TypeOf((*MockAchievementRepository)(nil).ReadAllAchievements))
}

// ReadUnlockedAchievementByAchievementID mocks base method.
func (m *MockAchievementRepository) ReadUnlockedAchievementByAchievementID(arg0 int64) (*model.UserAchievement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadUnlockedAchievementByAchievementID", arg0)
	ret0, _ := ret[0].(*model.UserAchievement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadUnlockedAchievementByAchievementID indicates an expected call of ReadUnlockedAchievementByAchievementID.
func (mr *MockAchievementRepositoryMockRecorder) ReadUnlockedAchievementByAchievementID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadUnlockedAchievementByAchievementID", reflect.TypeOf((*MockAchievementRepository)(nil).ReadUnlockedAchievementByAchievementID), arg0)
}

// ReadUnlockedAchievements mocks base method.
func (m *MockAchievementRepository) ReadUnlockedAchievements(arg0 int64) ([]*model.UserAchievement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadUnlockedAchievements", arg0)
	ret0, _ := ret[0].([]*model.UserAchievement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadUnlockedAchievements indicates an expected call of ReadUnlockedAchievements.
func (mr *MockAchievementRepositoryMockRecorder) ReadUnlockedAchievements(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadUnlockedAchievements", reflect.TypeOf((*MockAchievementRepository)(nil).ReadUnlockedAchievements), arg0)
}
