// Code generated by MockGen. DO NOT EDIT.
// Source: workoutpal/src/internal/domain/repository (interfaces: AchievementRepository)

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"
	model "workoutpal/src/internal/model"

	gomock "github.com/golang/mock/gomock"
)

// MockAchievementRepository is a mock of AchievementRepository interface.
type MockAchievementRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAchievementRepositoryMockRecorder
}

// MockAchievementRepositoryMockRecorder is the mock recorder for MockAchievementRepository.
type MockAchievementRepositoryMockRecorder struct {
	mock *MockAchievementRepository
}

// NewMockAchievementRepository creates a new mock instance.
func NewMockAchievementRepository(ctrl *gomock.Controller) *MockAchievementRepository {
	mock := &MockAchievementRepository{ctrl: ctrl}
	mock.recorder = &MockAchievementRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAchievementRepository) EXPECT() *MockAchievementRepositoryMockRecorder {
	return m.recorder
}

// CreateAchievement mocks base method.
func (m *MockAchievementRepository) CreateAchievement(arg0 model.CreateAchievementRequest) (*model.Achievement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAchievement", arg0)
	ret0, _ := ret[0].(*model.Achievement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAchievement indicates an expected call of CreateAchievement.
func (mr *MockAchievementRepositoryMockRecorder) CreateAchievement(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAchievement", reflect.TypeOf((*MockAchievementRepository)(nil).CreateAchievement), arg0)
}

// DeleteAchievement mocks base method.
func (m *MockAchievementRepository) DeleteAchievement(arg0 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAchievement", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAchievement indicates an expected call of DeleteAchievement.
func (mr *MockAchievementRepositoryMockRecorder) DeleteAchievement(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAchievement", reflect.TypeOf((*MockAchievementRepository)(nil).DeleteAchievement), arg0)
}

// ReadAchievements mocks base method.
func (m *MockAchievementRepository) ReadAchievements(arg0 int64) ([]*model.Achievement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAchievements", arg0)
	ret0, _ := ret[0].([]*model.Achievement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAchievements indicates an expected call of ReadAchievements.
func (mr *MockAchievementRepositoryMockRecorder) ReadAchievements(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAchievements", reflect.TypeOf((*MockAchievementRepository)(nil).ReadAchievements), arg0)
}
